// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoSkMZ6BvpTfQLtllrGDrxqNwpfSEaDvE',
    appId: '1:1051290621672:web:7328ce20eb05bd996a5b5d',
    messagingSenderId: '1051290621672',
    projectId: 'emart-firebase-app',
    authDomain: 'emart-firebase-app.firebaseapp.com',
    storageBucket: 'emart-firebase-app.appspot.com',
    measurementId: 'G-BJR8Y8QY6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAleiOBN0mjkzeEems1RyTH7Vi4pay5U',
    appId: '1:1051290621672:android:67d61b1badc42d456a5b5d',
    messagingSenderId: '1051290621672',
    projectId: 'emart-firebase-app',
    storageBucket: 'emart-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF7pKj_EWjHVMXWjyvg7kAdA6bCMizTr0',
    appId: '1:1051290621672:ios:ce0bf2e4c868ffde6a5b5d',
    messagingSenderId: '1051290621672',
    projectId: 'emart-firebase-app',
    storageBucket: 'emart-firebase-app.appspot.com',
    iosBundleId: 'com.example.emartFirebaseApp',
  );
}
